FROM php:5.6-apache
LABEL  maintainer "Kazuhiro Uchimura <uchimura@pencil.co.jp>"
ADD php.ini /usr/local/etc/php/conf.d/php.ini

#TBC.
#RUN apt-get update && docker-php-ext-install pdo_mysql mysqli mbstring
