version: '2'
services:

  data:
    image: busybox
    volumes:
      - ./misc/data:/var/lib/mysql

  rdb:
    image: mariadb:5.5
    container_name: rdb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev_password
    ports:
      - "13306:3306"
    volumes_from:
      - data
    volumes:
      - ./application/sql/initial.sql:/docker-entrypoint-initdb.d/initial.sql  # modify your application case.

  logs:
    image: busybox
    volumes:
      - ./misc/apache2:/var/log/httpd

  webapp:
    build: ./docker-webapp
    container_name: webapp
    ports:
      - "80:80"
      - "443:443"
    volumes_from:
      - logs
    volumes:
      - ./public_html:/var/www/vhosts/localhost.localdomain.tld/htdocs  # modify your working dierctory
    links:
      - rdb
    environment:
      DATABASE_HOST: 'rdb'
      DATABASE_NAME: 'mydb'
      DATABASE_USER: 'dev'
      DATABASE_PASSWORD: 'dev_password'
    privileged: true
    command: /sbin/init
